-- BẢNG VAI TRÒ NGƯỜI DÙNG
CREATE TABLE VaiTro (
  MaVT INT IDENTITY(1,1) PRIMARY KEY,
  TenVT NVARCHAR(50) NOT NULL UNIQUE -- VD: Admin, Quản lý, Thu ngân, Phục vụ
);

-- BẢNG NHÂN VIÊN
CREATE TABLE NhanVien (
  MaNV INT IDENTITY(1,1) PRIMARY KEY,
  HoTen NVARCHAR(200) NOT NULL,
  SDT NVARCHAR(20),
  Email NVARCHAR(200),
  NgayVaoLam DATE,
  TrangThai BIT DEFAULT 1 -- 1 = còn làm, 0 = nghỉ
);

-- BẢNG NGƯỜI DÙNG (TÀI KHOẢN ĐĂNG NHẬP)
CREATE TABLE NguoiDung (
  MaND INT IDENTITY(1,1) PRIMARY KEY,
  TenDN NVARCHAR(100) NOT NULL UNIQUE, -- Username
  MatKhau NVARCHAR(256) NOT NULL,      -- Password (demo: lưu text/hash)
  MaNV INT NULL,
  MaVT INT NOT NULL,
  NgayTao DATETIME2 DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_NguoiDung_NhanVien FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV),
  CONSTRAINT FK_NguoiDung_VaiTro FOREIGN KEY (MaVT) REFERENCES VaiTro(MaVT)
);

-- BẢNG BÀN
CREATE TABLE Ban (
  MaBan INT IDENTITY(1,1) PRIMARY KEY,
  TenBan NVARCHAR(50) NOT NULL,
  SoCho INT DEFAULT 4,
  TrangThai NVARCHAR(20) DEFAULT N'Trống' -- Trống, Có khách, Đã đặt, Cần dọn
);

-- BẢNG DANH MỤC & MÓN
CREATE TABLE DanhMuc (
  MaDM INT IDENTITY(1,1) PRIMARY KEY,
  TenDM NVARCHAR(100) NOT NULL,
  MoTa NVARCHAR(500)
);

CREATE TABLE Mon (
  MaMon INT IDENTITY(1,1) PRIMARY KEY,
  MaDM INT NULL,
  TenMon NVARCHAR(200) NOT NULL,
  DonGia DECIMAL(18,2) NOT NULL CHECK (DonGia >= 0),
  GiaVon DECIMAL(18,2) NULL,
  HoatDong BIT DEFAULT 1,
  CONSTRAINT FK_Mon_DanhMuc FOREIGN KEY (MaDM) REFERENCES DanhMuc(MaDM)
);

-- BẢNG KHÁCH HÀNG (thẻ thành viên)
CREATE TABLE KhachHang (
  MaKH INT IDENTITY(1,1) PRIMARY KEY,
  HoTen NVARCHAR(200),
  SDT NVARCHAR(20) UNIQUE,
  Email NVARCHAR(200),
  DiemTL INT DEFAULT 0, -- Điểm tích lũy
  ThanhVien BIT DEFAULT 0
);

-- BẢNG KHUYẾN MÃI
CREATE TABLE KhuyenMai (
  MaKM INT IDENTITY(1,1) PRIMARY KEY,
  MaCode NVARCHAR(50) UNIQUE,
  MoTa NVARCHAR(500),
  GiamPT DECIMAL(5,2) NULL,     -- giảm theo %
  GiamTien DECIMAL(18,2) NULL,  -- giảm số tiền cố định
  BatDau DATETIME2 NULL,
  KetThuc DATETIME2 NULL,
  HoatDong BIT DEFAULT 1
);

-- BẢNG HÓA ĐƠN
CREATE TABLE HoaDon (
  MaHD INT IDENTITY(1,1) PRIMARY KEY,
  SoHD NVARCHAR(50) NOT NULL UNIQUE,
  MaBan INT NULL,
  MaND INT NOT NULL, -- NV mở hóa đơn
  MaKH INT NULL,
  NgayTao DATETIME2 DEFAULT SYSUTCDATETIME(),
  NgayDong DATETIME2 NULL,
  TrangThai NVARCHAR(20) DEFAULT N'Mở', -- Mở, Đã thanh toán, Hủy
  TamTinh DECIMAL(18,2) DEFAULT 0,
  Giam DECIMAL(18,2) DEFAULT 0,
  Thue DECIMAL(18,2) DEFAULT 0,
  PhiPV DECIMAL(18,2) DEFAULT 0, -- phí phục vụ
  TongTien DECIMAL(18,2) DEFAULT 0,
  MaKM INT NULL,
  CONSTRAINT FK_HoaDon_Ban FOREIGN KEY (MaBan) REFERENCES Ban(MaBan),
  CONSTRAINT FK_HoaDon_NguoiDung FOREIGN KEY (MaND) REFERENCES NguoiDung(MaND),
  CONSTRAINT FK_HoaDon_KhachHang FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH),
  CONSTRAINT FK_HoaDon_KM FOREIGN KEY (MaKM) REFERENCES KhuyenMai(MaKM)
);

-- BẢNG CHI TIẾT HÓA ĐƠN
CREATE TABLE CTHoaDon (
  MaCTHD INT IDENTITY(1,1) PRIMARY KEY,
  MaHD INT NOT NULL,
  MaMon INT NOT NULL,
  SL INT NOT NULL CHECK (SL > 0),
  DonGia DECIMAL(18,2) NOT NULL,
  Giam DECIMAL(18,2) DEFAULT 0,
  ThanhTien AS (SL * DonGia - Giam) PERSISTED,
  CONSTRAINT FK_CTHoaDon_HoaDon FOREIGN KEY (MaHD) REFERENCES HoaDon(MaHD) ON DELETE CASCADE,
  CONSTRAINT FK_CTHoaDon_Mon FOREIGN KEY (MaMon) REFERENCES Mon(MaMon)
);

-- BẢNG THANH TOÁN
CREATE TABLE ThanhToan (
  MaTT INT IDENTITY(1,1) PRIMARY KEY,
  MaHD INT NOT NULL,
  SoTien DECIMAL(18,2) NOT NULL CHECK (SoTien>=0),
  HinhThuc NVARCHAR(50) NOT NULL, -- Tiền mặt, Thẻ, Momo, v.v.
  NgayTT DATETIME2 DEFAULT SYSUTCDATETIME(),
  GhiChu NVARCHAR(500),
  CONSTRAINT FK_ThanhToan_HoaDon FOREIGN KEY (MaHD) REFERENCES HoaDon(MaHD)
);


